source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HorizonteNovasMidias/ios-pod-specs.git'

platform :ios, '9.0'
use_frameworks!

def common_pods
  pod 'GSATActionCableClient', :path => '../'
  pod 'SwiftyJSON', '~> 3.0.2'
  pod 'SnapKit', '~> 4.0.0'
end

def common_test_pods
  pod 'Quick', '~> 0.9.3'
  pod 'Nimble', '3.2.0'
end

target 'ActionCableClient-Example-iOS' do
    common_pods
end

target 'ActionCableClient-Example-tvOS' do
    common_pods
end
